name: last homework(

on:
  push:
  pull_request:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: install go
        uses: actions/checkout@v2

      - name: Set up Go 1.13
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'

      - name: testing project
        run: go test ./...
